# Generated by Django 4.0.2 on 2022-03-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CambioMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=50)),
                ('fecha_actualizacion', models.CharField(max_length=50)),
                ('valorUSD', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CambioMoneda',
                'verbose_name_plural': 'CambioMonedas',
            },
        ),
    ]
